FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/PosCorte.Web/PosCorte.Web.csproj", "src/PosCorte.Web/"]
RUN dotnet restore "src/PosCorte.Web/PosCorte.Web.csproj"
COPY . .
WORKDIR "/src/src/PosCorte.Web"
RUN dotnet build "PosCorte.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PosCorte.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "PosCorte.Web.dll"]
