name: CD - Deploy Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy para Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: poscorte-api
